
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;

namespace DefectTracker.Server.Data
{

    public partial class DefecttrackerContext : DbContext
    {
        public DefecttrackerContext()
        {
        }

        public DefecttrackerContext(DbContextOptions<DefecttrackerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DefectDetails> DefectDetails { get; set; }
        public virtual DbSet<Defects> Defects { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DefectDetails>(entity =>
            {
                entity.Property(e => e.DefectAt).HasColumnType("datetime");

                entity.Property(e => e.DefectDescription).IsRequired();

                entity.HasOne(d => d.Defect)
                    .WithMany(p => p.DefectDetails)
                    .HasForeignKey(d => d.DefectId)
                    .HasConstraintName("FK_DefectDetails_Defects");
            });

            modelBuilder.Entity<Defects>(entity =>
            {
                entity.Property(e => e.DefectAt).HasColumnType("datetime");

                entity.Property(e => e.DefectDescription).IsRequired();

                entity.Property(e => e.DefectGuid)
                    .IsRequired()
                    .HasColumnName("DefectGUID")
                    .HasMaxLength(500);

                entity.Property(e => e.DefectReporterEmail)
                    .IsRequired()
                    .HasMaxLength(500);

                entity.Property(e => e.DefectStatus)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}