
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace DefectTracker.Server.Data
{
    public partial class Defects
    {
        public Defects()
        {
            DefectDetails = new HashSet<DefectDetails>();
        }

        public int Id { get; set; }
        public string DefectStatus { get; set; }
        public DateTime DefectAt { get; set; }
        public string DefectDescription { get; set; }
        public string DefectReporterEmail { get; set; }
        public string DefectGuid { get; set; }

        public virtual ICollection<DefectDetails> DefectDetails { get; set; }

    }
}
