// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DefectTracker.Server.Data
{
    public partial class DefectDetails
    {
        public int Id { get; set; }
        public int DefectId { get; set; }
        public DateTime DefectAt { get; set; }
        public string DefectDescription { get; set; }

        public virtual Defects Defect { get; set; }
    }
}